name: CI

on: push

jobs:
  test:
    name: ${{ matrix.lisp }} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl, ccl]

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        env:
          LISP: ${{ matrix.lisp }}
        run: make
